name: A06 Kernel Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLANG_DIR: toolchains/clang
      GCC_DIR: toolchains/gnu
      DEVICE_MODULES_DIR: kernel_device_modules-6.6
      OUT_DIR: ${{ github.workspace }}/out/target/product/a06/obj/KLEAF_OBJ
      DIST_DIR: ${{ github.workspace }}/out/target/product/a06/obj/KLEAF_OBJ/dist
      DEFCONFIG_OVERLAYS: "mt6768_overlay.config o8.config"
      PROJECT: "mgk_64_k66"
      MODE: "${{ github.actor }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev \
            x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev \
            libxml2-utils xsltproc unzip python3 python-is-python3 ccache tar wget

      - name: Enable ccache
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          ccache --max-size=10G
          echo "CCACHE_DIR=$GITHUB_WORKSPACE/.ccache" >> $GITHUB_ENV

      - name: Prepare repo binary
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > $GITHUB_WORKSPACE/bin/repo
          chmod a+x $GITHUB_WORKSPACE/bin/repo
          echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV

      - name: Kernel repo initialization and sync
        run: |
          export PATH="$GITHUB_WORKSPACE/bin:$PATH"
          mkdir -p kernel_build
          cd kernel_build
          if [ ! -d ".repo" ]; then
            repo init -u https://android.googlesource.com/kernel/manifest \
              -b common-android15-6.6 --depth=1 --quiet --no-repo-verify
          fi
          repo sync -j$(nproc) --no-clone-bundle --quiet --force-sync

      - name: Fetch toolchains
        run: |
          mkdir -p $GITHUB_WORKSPACE/toolchains
          cd $GITHUB_WORKSPACE/toolchains

          # Clang 18 by default
          if [ ! -d "$CLANG_DIR" ]; then
            mkdir -p "$CLANG_DIR"
            cd "$CLANG_DIR"
            wget -q -O clang18.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz
            tar -xf clang18.tar.gz
            rm clang18.tar.gz
            cd ..
          fi

          # GCC 6.4
          if [ ! -d "$GCC_DIR" ]; then
            git clone --depth=1 https://github.com/rsuntk/toolchains.git -b gcc-6.4 "$GCC_DIR"
          fi

      - name: Ensure output directories
        run: |
          mkdir -p "$OUT_DIR" "$DIST_DIR"

      - name: Generate build.config with debug
        run: |
          cd kernel
          BUILD_CONFIG="$GITHUB_WORKSPACE/kernel/build.config"
          python $DEVICE_MODULES_DIR/scripts/gen_build_config.py \
            --kernel-defconfig mediatek-bazel_defconfig \
            --kernel-defconfig-overlays "$DEFCONFIG_OVERLAYS" \
            --kernel-build-config-overlays "" \
            -m "$MODE" \
            -o "$BUILD_CONFIG"

          echo "Checking build.config existence..."
          if [ -f "$BUILD_CONFIG" ]; then
            echo "✅ build.config successfully created at $BUILD_CONFIG"
          else
            echo "❌ Error: build.config was not created at $BUILD_CONFIG"
            echo "Listing kernel_device_modules-6.6/scripts contents:"
            ls -l $DEVICE_MODULES_DIR/scripts
            echo "Listing kernel directory contents:"
            ls -l .
            exit 1
          fi
          echo "BUILD_CONFIG=$BUILD_CONFIG" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          cd kernel
          source "$BUILD_CONFIG"
          ./kernel_device_modules-6.6/build.sh

      - name: Show ccache stats
        run: |
          ccache --show-stats

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: out/arch/arm64/boot/Image.gz-dtb
